package org.java.luke.baedb.dao;

import java.util.List;

import org.java.luke.baedb.model.Mytest01;
import org.java.luke.baedb.model.Mytest01Criteria;
import org.apache.ibatis.annotations.Param;

public interface Mytest01Mapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	int countByExample(@Param("example") Mytest01Criteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(@Param("example") Mytest01Criteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	int insertSelective(@Param("record") Mytest01 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	List<Mytest01> selectByExample(@Param("example") Mytest01Criteria example, @Param("record_start") int record_start,
			@Param("record_stop") int record_stop, @Param("record_max_count") int record_max_count);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Mytest01 record, @Param("example") Mytest01Criteria example);
	
	int flushCache();
}
