package org.java.luke.baedb.dao;

import java.util.List;

import org.java.luke.baedb.model.Pcpn;
import org.java.luke.baedb.model.PcpnCriteria;
import org.apache.ibatis.annotations.Param;

public interface PcpnMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	int countByExample(@Param("example") PcpnCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(@Param("example") PcpnCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	int insertSelective(@Param("record") Pcpn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	List<Pcpn> selectByExample(@Param("example") PcpnCriteria example, @Param("record_start") int record_start,
			@Param("record_stop") int record_stop, @Param("record_max_count") int record_max_count);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table S014809.L_AMBRY
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Pcpn record, @Param("example") PcpnCriteria example);
	
	int flushCache();
}
