package org.java.luke.baedb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.luke.baedb.model.Mytest01;
import org.java.luke.baedb.model.Mytest01Criteria;

public interface Mytest01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int countByExample(Mytest01Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int deleteByExample(Mytest01Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int insert(Mytest01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int insertSelective(Mytest01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    List<Mytest01> selectByExample(Mytest01Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    Mytest01 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Mytest01 record, @Param("example") Mytest01Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Mytest01 record, @Param("example") Mytest01Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mytest01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MYTEST01
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mytest01 record);
}