package org.java.luke.baedb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.luke.baedb.model.Tabletest;
import org.java.luke.baedb.model.TabletestCriteria;

public interface TabletestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int countByExample(TabletestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int deleteByExample(TabletestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int insert(Tabletest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int insertSelective(Tabletest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    List<Tabletest> selectByExample(TabletestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    Tabletest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tabletest record, @Param("example") TabletestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tabletest record, @Param("example") TabletestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tabletest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabletest
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tabletest record);
}