package org.java.luke.baedb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.luke.baedb.model.Carreg;
import org.java.luke.baedb.model.CarregCriteria;

public interface CarregMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int countByExample(CarregCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int deleteByExample(CarregCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int insert(Carreg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int insertSelective(Carreg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    List<Carreg> selectByExample(CarregCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    Carreg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Carreg record, @Param("example") CarregCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Carreg record, @Param("example") CarregCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Carreg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarReg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Carreg record);
}