package org.java.luke.baedb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.luke.baedb.model.Cppn;
import org.java.luke.baedb.model.CppnCriteria;

public interface CppnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int countByExample(CppnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int deleteByExample(CppnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int insert(Cppn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int insertSelective(Cppn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    List<Cppn> selectByExample(CppnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    Cppn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Cppn record, @Param("example") CppnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Cppn record, @Param("example") CppnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cppn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cppn record);
}