package org.java.luke.baedb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.luke.baedb.model.Cprelation;
import org.java.luke.baedb.model.CprelationCriteria;

public interface CprelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int countByExample(CprelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int deleteByExample(CprelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int insert(Cprelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int insertSelective(Cprelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    List<Cprelation> selectByExample(CprelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    Cprelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Cprelation record, @Param("example") CprelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Cprelation record, @Param("example") CprelationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cprelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPRelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cprelation record);
}