package org.java.luke.baedb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.luke.baedb.model.Pcpn;
import org.java.luke.baedb.model.PcpnCriteria;

public interface PcpnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int countByExample(PcpnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int deleteByExample(PcpnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int insert(Pcpn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int insertSelective(Pcpn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    List<Pcpn> selectByExample(PcpnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    Pcpn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Pcpn record, @Param("example") PcpnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Pcpn record, @Param("example") PcpnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pcpn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PCPN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pcpn record);
}