package org.java.luke.baedb.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.luke.baedb.model.Pnmessage;
import org.java.luke.baedb.model.PnmessageCriteria;

public interface PnmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int countByExample(PnmessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int deleteByExample(PnmessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int insert(Pnmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int insertSelective(Pnmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    List<Pnmessage> selectByExample(PnmessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    Pnmessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Pnmessage record, @Param("example") PnmessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Pnmessage record, @Param("example") PnmessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pnmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PNMessage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pnmessage record);
}