package org.java.luke.baedb.model;

public class Cprannum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRanNum.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRanNum.encodedKey
     *
     * @mbggenerated
     */
    private String encodedKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRanNum.carID
     *
     * @mbggenerated
     */
    private String carID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRanNum.randomID
     *
     * @mbggenerated
     */
    private String randomID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRanNum.deadTime
     *
     * @mbggenerated
     */
    private String deadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRanNum.isPrimary
     *
     * @mbggenerated
     */
    private String isPrimary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRanNum.id
     *
     * @return the value of CPRanNum.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRanNum.id
     *
     * @param id the value for CPRanNum.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRanNum.encodedKey
     *
     * @return the value of CPRanNum.encodedKey
     *
     * @mbggenerated
     */
    public String getEncodedKey() {
        return encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRanNum.encodedKey
     *
     * @param encodedKey the value for CPRanNum.encodedKey
     *
     * @mbggenerated
     */
    public void setEncodedKey(String encodedKey) {
        this.encodedKey = encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRanNum.carID
     *
     * @return the value of CPRanNum.carID
     *
     * @mbggenerated
     */
    public String getCarID() {
        return carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRanNum.carID
     *
     * @param carID the value for CPRanNum.carID
     *
     * @mbggenerated
     */
    public void setCarID(String carID) {
        this.carID = carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRanNum.randomID
     *
     * @return the value of CPRanNum.randomID
     *
     * @mbggenerated
     */
    public String getRandomID() {
        return randomID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRanNum.randomID
     *
     * @param randomID the value for CPRanNum.randomID
     *
     * @mbggenerated
     */
    public void setRandomID(String randomID) {
        this.randomID = randomID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRanNum.deadTime
     *
     * @return the value of CPRanNum.deadTime
     *
     * @mbggenerated
     */
    public String getDeadTime() {
        return deadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRanNum.deadTime
     *
     * @param deadTime the value for CPRanNum.deadTime
     *
     * @mbggenerated
     */
    public void setDeadTime(String deadTime) {
        this.deadTime = deadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRanNum.isPrimary
     *
     * @return the value of CPRanNum.isPrimary
     *
     * @mbggenerated
     */
    public String getIsPrimary() {
        return isPrimary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRanNum.isPrimary
     *
     * @param isPrimary the value for CPRanNum.isPrimary
     *
     * @mbggenerated
     */
    public void setIsPrimary(String isPrimary) {
        this.isPrimary = isPrimary;
    }
}