package org.java.luke.baedb.model;

public class Tabletest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tabletest.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tabletest.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tabletest.height
     *
     * @mbggenerated
     */
    private Integer height;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tabletest.id
     *
     * @return the value of tabletest.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tabletest.id
     *
     * @param id the value for tabletest.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tabletest.name
     *
     * @return the value of tabletest.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tabletest.name
     *
     * @param name the value for tabletest.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tabletest.height
     *
     * @return the value of tabletest.height
     *
     * @mbggenerated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tabletest.height
     *
     * @param height the value for tabletest.height
     *
     * @mbggenerated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }
}