package org.java.luke.baedb.model;

import java.util.ArrayList;
import java.util.List;

public class CppnCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public CppnCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyIsNull() {
            addCriterion("encodedKey is null");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyIsNotNull() {
            addCriterion("encodedKey is not null");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyEqualTo(String value) {
            addCriterion("encodedKey =", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyNotEqualTo(String value) {
            addCriterion("encodedKey <>", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyGreaterThan(String value) {
            addCriterion("encodedKey >", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyGreaterThanOrEqualTo(String value) {
            addCriterion("encodedKey >=", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyLessThan(String value) {
            addCriterion("encodedKey <", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyLessThanOrEqualTo(String value) {
            addCriterion("encodedKey <=", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyLike(String value) {
            addCriterion("encodedKey like", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyNotLike(String value) {
            addCriterion("encodedKey not like", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyIn(List<String> values) {
            addCriterion("encodedKey in", values, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyNotIn(List<String> values) {
            addCriterion("encodedKey not in", values, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyBetween(String value1, String value2) {
            addCriterion("encodedKey between", value1, value2, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyNotBetween(String value1, String value2) {
            addCriterion("encodedKey not between", value1, value2, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andCarIDIsNull() {
            addCriterion("carID is null");
            return (Criteria) this;
        }

        public Criteria andCarIDIsNotNull() {
            addCriterion("carID is not null");
            return (Criteria) this;
        }

        public Criteria andCarIDEqualTo(String value) {
            addCriterion("carID =", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDNotEqualTo(String value) {
            addCriterion("carID <>", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDGreaterThan(String value) {
            addCriterion("carID >", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDGreaterThanOrEqualTo(String value) {
            addCriterion("carID >=", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDLessThan(String value) {
            addCriterion("carID <", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDLessThanOrEqualTo(String value) {
            addCriterion("carID <=", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDLike(String value) {
            addCriterion("carID like", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDNotLike(String value) {
            addCriterion("carID not like", value, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDIn(List<String> values) {
            addCriterion("carID in", values, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDNotIn(List<String> values) {
            addCriterion("carID not in", values, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDBetween(String value1, String value2) {
            addCriterion("carID between", value1, value2, "carID");
            return (Criteria) this;
        }

        public Criteria andCarIDNotBetween(String value1, String value2) {
            addCriterion("carID not between", value1, value2, "carID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDIsNull() {
            addCriterion("phoneID is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIDIsNotNull() {
            addCriterion("phoneID is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneIDEqualTo(String value) {
            addCriterion("phoneID =", value, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDNotEqualTo(String value) {
            addCriterion("phoneID <>", value, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDGreaterThan(String value) {
            addCriterion("phoneID >", value, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDGreaterThanOrEqualTo(String value) {
            addCriterion("phoneID >=", value, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDLessThan(String value) {
            addCriterion("phoneID <", value, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDLessThanOrEqualTo(String value) {
            addCriterion("phoneID <=", value, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDLike(String value) {
            addCriterion("phoneID like", value, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDNotLike(String value) {
            addCriterion("phoneID not like", value, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDIn(List<String> values) {
            addCriterion("phoneID in", values, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDNotIn(List<String> values) {
            addCriterion("phoneID not in", values, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDBetween(String value1, String value2) {
            addCriterion("phoneID between", value1, value2, "phoneID");
            return (Criteria) this;
        }

        public Criteria andPhoneIDNotBetween(String value1, String value2) {
            addCriterion("phoneID not between", value1, value2, "phoneID");
            return (Criteria) this;
        }

        public Criteria andMessageIDIsNull() {
            addCriterion("messageID is null");
            return (Criteria) this;
        }

        public Criteria andMessageIDIsNotNull() {
            addCriterion("messageID is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIDEqualTo(String value) {
            addCriterion("messageID =", value, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDNotEqualTo(String value) {
            addCriterion("messageID <>", value, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDGreaterThan(String value) {
            addCriterion("messageID >", value, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDGreaterThanOrEqualTo(String value) {
            addCriterion("messageID >=", value, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDLessThan(String value) {
            addCriterion("messageID <", value, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDLessThanOrEqualTo(String value) {
            addCriterion("messageID <=", value, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDLike(String value) {
            addCriterion("messageID like", value, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDNotLike(String value) {
            addCriterion("messageID not like", value, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDIn(List<String> values) {
            addCriterion("messageID in", values, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDNotIn(List<String> values) {
            addCriterion("messageID not in", values, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDBetween(String value1, String value2) {
            addCriterion("messageID between", value1, value2, "messageID");
            return (Criteria) this;
        }

        public Criteria andMessageIDNotBetween(String value1, String value2) {
            addCriterion("messageID not between", value1, value2, "messageID");
            return (Criteria) this;
        }

        public Criteria andIsSendIsNull() {
            addCriterion("isSend is null");
            return (Criteria) this;
        }

        public Criteria andIsSendIsNotNull() {
            addCriterion("isSend is not null");
            return (Criteria) this;
        }

        public Criteria andIsSendEqualTo(String value) {
            addCriterion("isSend =", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendNotEqualTo(String value) {
            addCriterion("isSend <>", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendGreaterThan(String value) {
            addCriterion("isSend >", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendGreaterThanOrEqualTo(String value) {
            addCriterion("isSend >=", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendLessThan(String value) {
            addCriterion("isSend <", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendLessThanOrEqualTo(String value) {
            addCriterion("isSend <=", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendLike(String value) {
            addCriterion("isSend like", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendNotLike(String value) {
            addCriterion("isSend not like", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendIn(List<String> values) {
            addCriterion("isSend in", values, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendNotIn(List<String> values) {
            addCriterion("isSend not in", values, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendBetween(String value1, String value2) {
            addCriterion("isSend between", value1, value2, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendNotBetween(String value1, String value2) {
            addCriterion("isSend not between", value1, value2, "isSend");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("addTime is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("addTime is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(String value) {
            addCriterion("addTime =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(String value) {
            addCriterion("addTime <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(String value) {
            addCriterion("addTime >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(String value) {
            addCriterion("addTime >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(String value) {
            addCriterion("addTime <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(String value) {
            addCriterion("addTime <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLike(String value) {
            addCriterion("addTime like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotLike(String value) {
            addCriterion("addTime not like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<String> values) {
            addCriterion("addTime in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<String> values) {
            addCriterion("addTime not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(String value1, String value2) {
            addCriterion("addTime between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(String value1, String value2) {
            addCriterion("addTime not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNull() {
            addCriterion("modTime is null");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNotNull() {
            addCriterion("modTime is not null");
            return (Criteria) this;
        }

        public Criteria andModTimeEqualTo(String value) {
            addCriterion("modTime =", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotEqualTo(String value) {
            addCriterion("modTime <>", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThan(String value) {
            addCriterion("modTime >", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThanOrEqualTo(String value) {
            addCriterion("modTime >=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThan(String value) {
            addCriterion("modTime <", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThanOrEqualTo(String value) {
            addCriterion("modTime <=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLike(String value) {
            addCriterion("modTime like", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotLike(String value) {
            addCriterion("modTime not like", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIn(List<String> values) {
            addCriterion("modTime in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotIn(List<String> values) {
            addCriterion("modTime not in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeBetween(String value1, String value2) {
            addCriterion("modTime between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotBetween(String value1, String value2) {
            addCriterion("modTime not between", value1, value2, "modTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CPPN
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CPPN
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}