package org.java.luke.baedb.model;

public class Cprelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRelation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRelation.encodedKey
     *
     * @mbggenerated
     */
    private String encodedKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRelation.carID
     *
     * @mbggenerated
     */
    private String carID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRelation.phoneID
     *
     * @mbggenerated
     */
    private String phoneID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRelation.isPrimary
     *
     * @mbggenerated
     */
    private String isPrimary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRelation.addTime
     *
     * @mbggenerated
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CPRelation.modTime
     *
     * @mbggenerated
     */
    private String modTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRelation.id
     *
     * @return the value of CPRelation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRelation.id
     *
     * @param id the value for CPRelation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRelation.encodedKey
     *
     * @return the value of CPRelation.encodedKey
     *
     * @mbggenerated
     */
    public String getEncodedKey() {
        return encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRelation.encodedKey
     *
     * @param encodedKey the value for CPRelation.encodedKey
     *
     * @mbggenerated
     */
    public void setEncodedKey(String encodedKey) {
        this.encodedKey = encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRelation.carID
     *
     * @return the value of CPRelation.carID
     *
     * @mbggenerated
     */
    public String getCarID() {
        return carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRelation.carID
     *
     * @param carID the value for CPRelation.carID
     *
     * @mbggenerated
     */
    public void setCarID(String carID) {
        this.carID = carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRelation.phoneID
     *
     * @return the value of CPRelation.phoneID
     *
     * @mbggenerated
     */
    public String getPhoneID() {
        return phoneID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRelation.phoneID
     *
     * @param phoneID the value for CPRelation.phoneID
     *
     * @mbggenerated
     */
    public void setPhoneID(String phoneID) {
        this.phoneID = phoneID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRelation.isPrimary
     *
     * @return the value of CPRelation.isPrimary
     *
     * @mbggenerated
     */
    public String getIsPrimary() {
        return isPrimary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRelation.isPrimary
     *
     * @param isPrimary the value for CPRelation.isPrimary
     *
     * @mbggenerated
     */
    public void setIsPrimary(String isPrimary) {
        this.isPrimary = isPrimary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRelation.addTime
     *
     * @return the value of CPRelation.addTime
     *
     * @mbggenerated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRelation.addTime
     *
     * @param addTime the value for CPRelation.addTime
     *
     * @mbggenerated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CPRelation.modTime
     *
     * @return the value of CPRelation.modTime
     *
     * @mbggenerated
     */
    public String getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CPRelation.modTime
     *
     * @param modTime the value for CPRelation.modTime
     *
     * @mbggenerated
     */
    public void setModTime(String modTime) {
        this.modTime = modTime;
    }
}