package org.java.luke.baedb.model;

public class Mytest01 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYTEST01.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYTEST01.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MYTEST01.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYTEST01.id
     *
     * @return the value of MYTEST01.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYTEST01.id
     *
     * @param id the value for MYTEST01.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYTEST01.name
     *
     * @return the value of MYTEST01.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYTEST01.name
     *
     * @param name the value for MYTEST01.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MYTEST01.value
     *
     * @return the value of MYTEST01.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MYTEST01.value
     *
     * @param value the value for MYTEST01.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value;
    }
}