package org.java.luke.baedb.model;

public class Pcpn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCPN.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCPN.encodedKey
     *
     * @mbggenerated
     */
    private String encodedKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCPN.carID
     *
     * @mbggenerated
     */
    private String carID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCPN.phoneID
     *
     * @mbggenerated
     */
    private String phoneID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCPN.messageID
     *
     * @mbggenerated
     */
    private String messageID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCPN.isSend
     *
     * @mbggenerated
     */
    private String isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCPN.addTime
     *
     * @mbggenerated
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PCPN.modTime
     *
     * @mbggenerated
     */
    private String modTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCPN.id
     *
     * @return the value of PCPN.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCPN.id
     *
     * @param id the value for PCPN.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCPN.encodedKey
     *
     * @return the value of PCPN.encodedKey
     *
     * @mbggenerated
     */
    public String getEncodedKey() {
        return encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCPN.encodedKey
     *
     * @param encodedKey the value for PCPN.encodedKey
     *
     * @mbggenerated
     */
    public void setEncodedKey(String encodedKey) {
        this.encodedKey = encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCPN.carID
     *
     * @return the value of PCPN.carID
     *
     * @mbggenerated
     */
    public String getCarID() {
        return carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCPN.carID
     *
     * @param carID the value for PCPN.carID
     *
     * @mbggenerated
     */
    public void setCarID(String carID) {
        this.carID = carID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCPN.phoneID
     *
     * @return the value of PCPN.phoneID
     *
     * @mbggenerated
     */
    public String getPhoneID() {
        return phoneID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCPN.phoneID
     *
     * @param phoneID the value for PCPN.phoneID
     *
     * @mbggenerated
     */
    public void setPhoneID(String phoneID) {
        this.phoneID = phoneID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCPN.messageID
     *
     * @return the value of PCPN.messageID
     *
     * @mbggenerated
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCPN.messageID
     *
     * @param messageID the value for PCPN.messageID
     *
     * @mbggenerated
     */
    public void setMessageID(String messageID) {
        this.messageID = messageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCPN.isSend
     *
     * @return the value of PCPN.isSend
     *
     * @mbggenerated
     */
    public String getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCPN.isSend
     *
     * @param isSend the value for PCPN.isSend
     *
     * @mbggenerated
     */
    public void setIsSend(String isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCPN.addTime
     *
     * @return the value of PCPN.addTime
     *
     * @mbggenerated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCPN.addTime
     *
     * @param addTime the value for PCPN.addTime
     *
     * @mbggenerated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PCPN.modTime
     *
     * @return the value of PCPN.modTime
     *
     * @mbggenerated
     */
    public String getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PCPN.modTime
     *
     * @param modTime the value for PCPN.modTime
     *
     * @mbggenerated
     */
    public void setModTime(String modTime) {
        this.modTime = modTime;
    }
}