package org.java.luke.baedb.model;

import java.util.ArrayList;
import java.util.List;

public class PhoneregCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public PhoneregCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyIsNull() {
            addCriterion("encodedKey is null");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyIsNotNull() {
            addCriterion("encodedKey is not null");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyEqualTo(String value) {
            addCriterion("encodedKey =", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyNotEqualTo(String value) {
            addCriterion("encodedKey <>", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyGreaterThan(String value) {
            addCriterion("encodedKey >", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyGreaterThanOrEqualTo(String value) {
            addCriterion("encodedKey >=", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyLessThan(String value) {
            addCriterion("encodedKey <", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyLessThanOrEqualTo(String value) {
            addCriterion("encodedKey <=", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyLike(String value) {
            addCriterion("encodedKey like", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyNotLike(String value) {
            addCriterion("encodedKey not like", value, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyIn(List<String> values) {
            addCriterion("encodedKey in", values, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyNotIn(List<String> values) {
            addCriterion("encodedKey not in", values, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyBetween(String value1, String value2) {
            addCriterion("encodedKey between", value1, value2, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andEncodedKeyNotBetween(String value1, String value2) {
            addCriterion("encodedKey not between", value1, value2, "encodedKey");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIsNull() {
            addCriterion("deviceID is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIsNotNull() {
            addCriterion("deviceID is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIDEqualTo(String value) {
            addCriterion("deviceID =", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotEqualTo(String value) {
            addCriterion("deviceID <>", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDGreaterThan(String value) {
            addCriterion("deviceID >", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDGreaterThanOrEqualTo(String value) {
            addCriterion("deviceID >=", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDLessThan(String value) {
            addCriterion("deviceID <", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDLessThanOrEqualTo(String value) {
            addCriterion("deviceID <=", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDLike(String value) {
            addCriterion("deviceID like", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotLike(String value) {
            addCriterion("deviceID not like", value, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDIn(List<String> values) {
            addCriterion("deviceID in", values, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotIn(List<String> values) {
            addCriterion("deviceID not in", values, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDBetween(String value1, String value2) {
            addCriterion("deviceID between", value1, value2, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIDNotBetween(String value1, String value2) {
            addCriterion("deviceID not between", value1, value2, "deviceID");
            return (Criteria) this;
        }

        public Criteria andDeviceIPIsNull() {
            addCriterion("deviceIP is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIPIsNotNull() {
            addCriterion("deviceIP is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIPEqualTo(String value) {
            addCriterion("deviceIP =", value, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPNotEqualTo(String value) {
            addCriterion("deviceIP <>", value, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPGreaterThan(String value) {
            addCriterion("deviceIP >", value, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPGreaterThanOrEqualTo(String value) {
            addCriterion("deviceIP >=", value, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPLessThan(String value) {
            addCriterion("deviceIP <", value, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPLessThanOrEqualTo(String value) {
            addCriterion("deviceIP <=", value, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPLike(String value) {
            addCriterion("deviceIP like", value, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPNotLike(String value) {
            addCriterion("deviceIP not like", value, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPIn(List<String> values) {
            addCriterion("deviceIP in", values, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPNotIn(List<String> values) {
            addCriterion("deviceIP not in", values, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPBetween(String value1, String value2) {
            addCriterion("deviceIP between", value1, value2, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andDeviceIPNotBetween(String value1, String value2) {
            addCriterion("deviceIP not between", value1, value2, "deviceIP");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNull() {
            addCriterion("appVersion is null");
            return (Criteria) this;
        }

        public Criteria andAppVersionIsNotNull() {
            addCriterion("appVersion is not null");
            return (Criteria) this;
        }

        public Criteria andAppVersionEqualTo(String value) {
            addCriterion("appVersion =", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotEqualTo(String value) {
            addCriterion("appVersion <>", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThan(String value) {
            addCriterion("appVersion >", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionGreaterThanOrEqualTo(String value) {
            addCriterion("appVersion >=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThan(String value) {
            addCriterion("appVersion <", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLessThanOrEqualTo(String value) {
            addCriterion("appVersion <=", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionLike(String value) {
            addCriterion("appVersion like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotLike(String value) {
            addCriterion("appVersion not like", value, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionIn(List<String> values) {
            addCriterion("appVersion in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotIn(List<String> values) {
            addCriterion("appVersion not in", values, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionBetween(String value1, String value2) {
            addCriterion("appVersion between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andAppVersionNotBetween(String value1, String value2) {
            addCriterion("appVersion not between", value1, value2, "appVersion");
            return (Criteria) this;
        }

        public Criteria andSenderIDIsNull() {
            addCriterion("senderID is null");
            return (Criteria) this;
        }

        public Criteria andSenderIDIsNotNull() {
            addCriterion("senderID is not null");
            return (Criteria) this;
        }

        public Criteria andSenderIDEqualTo(String value) {
            addCriterion("senderID =", value, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDNotEqualTo(String value) {
            addCriterion("senderID <>", value, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDGreaterThan(String value) {
            addCriterion("senderID >", value, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDGreaterThanOrEqualTo(String value) {
            addCriterion("senderID >=", value, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDLessThan(String value) {
            addCriterion("senderID <", value, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDLessThanOrEqualTo(String value) {
            addCriterion("senderID <=", value, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDLike(String value) {
            addCriterion("senderID like", value, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDNotLike(String value) {
            addCriterion("senderID not like", value, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDIn(List<String> values) {
            addCriterion("senderID in", values, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDNotIn(List<String> values) {
            addCriterion("senderID not in", values, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDBetween(String value1, String value2) {
            addCriterion("senderID between", value1, value2, "senderID");
            return (Criteria) this;
        }

        public Criteria andSenderIDNotBetween(String value1, String value2) {
            addCriterion("senderID not between", value1, value2, "senderID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDIsNull() {
            addCriterion("registerID is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIDIsNotNull() {
            addCriterion("registerID is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIDEqualTo(String value) {
            addCriterion("registerID =", value, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDNotEqualTo(String value) {
            addCriterion("registerID <>", value, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDGreaterThan(String value) {
            addCriterion("registerID >", value, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDGreaterThanOrEqualTo(String value) {
            addCriterion("registerID >=", value, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDLessThan(String value) {
            addCriterion("registerID <", value, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDLessThanOrEqualTo(String value) {
            addCriterion("registerID <=", value, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDLike(String value) {
            addCriterion("registerID like", value, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDNotLike(String value) {
            addCriterion("registerID not like", value, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDIn(List<String> values) {
            addCriterion("registerID in", values, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDNotIn(List<String> values) {
            addCriterion("registerID not in", values, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDBetween(String value1, String value2) {
            addCriterion("registerID between", value1, value2, "registerID");
            return (Criteria) this;
        }

        public Criteria andRegisterIDNotBetween(String value1, String value2) {
            addCriterion("registerID not between", value1, value2, "registerID");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("addTime is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("addTime is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(String value) {
            addCriterion("addTime =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(String value) {
            addCriterion("addTime <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(String value) {
            addCriterion("addTime >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(String value) {
            addCriterion("addTime >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(String value) {
            addCriterion("addTime <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(String value) {
            addCriterion("addTime <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLike(String value) {
            addCriterion("addTime like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotLike(String value) {
            addCriterion("addTime not like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<String> values) {
            addCriterion("addTime in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<String> values) {
            addCriterion("addTime not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(String value1, String value2) {
            addCriterion("addTime between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(String value1, String value2) {
            addCriterion("addTime not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNull() {
            addCriterion("modTime is null");
            return (Criteria) this;
        }

        public Criteria andModTimeIsNotNull() {
            addCriterion("modTime is not null");
            return (Criteria) this;
        }

        public Criteria andModTimeEqualTo(String value) {
            addCriterion("modTime =", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotEqualTo(String value) {
            addCriterion("modTime <>", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThan(String value) {
            addCriterion("modTime >", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeGreaterThanOrEqualTo(String value) {
            addCriterion("modTime >=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThan(String value) {
            addCriterion("modTime <", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLessThanOrEqualTo(String value) {
            addCriterion("modTime <=", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeLike(String value) {
            addCriterion("modTime like", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotLike(String value) {
            addCriterion("modTime not like", value, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeIn(List<String> values) {
            addCriterion("modTime in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotIn(List<String> values) {
            addCriterion("modTime not in", values, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeBetween(String value1, String value2) {
            addCriterion("modTime between", value1, value2, "modTime");
            return (Criteria) this;
        }

        public Criteria andModTimeNotBetween(String value1, String value2) {
            addCriterion("modTime not between", value1, value2, "modTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PhoneReg
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PhoneReg
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}