package org.java.luke.baedb.model;

public class Phonereg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.encodedKey
     *
     * @mbggenerated
     */
    private String encodedKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.deviceID
     *
     * @mbggenerated
     */
    private String deviceID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.deviceIP
     *
     * @mbggenerated
     */
    private String deviceIP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.appVersion
     *
     * @mbggenerated
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.senderID
     *
     * @mbggenerated
     */
    private String senderID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.registerID
     *
     * @mbggenerated
     */
    private String registerID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.addTime
     *
     * @mbggenerated
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PhoneReg.modTime
     *
     * @mbggenerated
     */
    private String modTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.id
     *
     * @return the value of PhoneReg.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.id
     *
     * @param id the value for PhoneReg.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.encodedKey
     *
     * @return the value of PhoneReg.encodedKey
     *
     * @mbggenerated
     */
    public String getEncodedKey() {
        return encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.encodedKey
     *
     * @param encodedKey the value for PhoneReg.encodedKey
     *
     * @mbggenerated
     */
    public void setEncodedKey(String encodedKey) {
        this.encodedKey = encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.deviceID
     *
     * @return the value of PhoneReg.deviceID
     *
     * @mbggenerated
     */
    public String getDeviceID() {
        return deviceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.deviceID
     *
     * @param deviceID the value for PhoneReg.deviceID
     *
     * @mbggenerated
     */
    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.deviceIP
     *
     * @return the value of PhoneReg.deviceIP
     *
     * @mbggenerated
     */
    public String getDeviceIP() {
        return deviceIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.deviceIP
     *
     * @param deviceIP the value for PhoneReg.deviceIP
     *
     * @mbggenerated
     */
    public void setDeviceIP(String deviceIP) {
        this.deviceIP = deviceIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.appVersion
     *
     * @return the value of PhoneReg.appVersion
     *
     * @mbggenerated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.appVersion
     *
     * @param appVersion the value for PhoneReg.appVersion
     *
     * @mbggenerated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.senderID
     *
     * @return the value of PhoneReg.senderID
     *
     * @mbggenerated
     */
    public String getSenderID() {
        return senderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.senderID
     *
     * @param senderID the value for PhoneReg.senderID
     *
     * @mbggenerated
     */
    public void setSenderID(String senderID) {
        this.senderID = senderID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.registerID
     *
     * @return the value of PhoneReg.registerID
     *
     * @mbggenerated
     */
    public String getRegisterID() {
        return registerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.registerID
     *
     * @param registerID the value for PhoneReg.registerID
     *
     * @mbggenerated
     */
    public void setRegisterID(String registerID) {
        this.registerID = registerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.addTime
     *
     * @return the value of PhoneReg.addTime
     *
     * @mbggenerated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.addTime
     *
     * @param addTime the value for PhoneReg.addTime
     *
     * @mbggenerated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PhoneReg.modTime
     *
     * @return the value of PhoneReg.modTime
     *
     * @mbggenerated
     */
    public String getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PhoneReg.modTime
     *
     * @param modTime the value for PhoneReg.modTime
     *
     * @mbggenerated
     */
    public void setModTime(String modTime) {
        this.modTime = modTime;
    }
}