package org.java.luke.baedb.model;

public class Pnmessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PNMessage.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PNMessage.encodedKey
     *
     * @mbggenerated
     */
    private String encodedKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PNMessage.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PNMessage.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PNMessage.rowdata
     *
     * @mbggenerated
     */
    private String rowdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PNMessage.addTime
     *
     * @mbggenerated
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PNMessage.modTime
     *
     * @mbggenerated
     */
    private String modTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PNMessage.id
     *
     * @return the value of PNMessage.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PNMessage.id
     *
     * @param id the value for PNMessage.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PNMessage.encodedKey
     *
     * @return the value of PNMessage.encodedKey
     *
     * @mbggenerated
     */
    public String getEncodedKey() {
        return encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PNMessage.encodedKey
     *
     * @param encodedKey the value for PNMessage.encodedKey
     *
     * @mbggenerated
     */
    public void setEncodedKey(String encodedKey) {
        this.encodedKey = encodedKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PNMessage.title
     *
     * @return the value of PNMessage.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PNMessage.title
     *
     * @param title the value for PNMessage.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PNMessage.message
     *
     * @return the value of PNMessage.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PNMessage.message
     *
     * @param message the value for PNMessage.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PNMessage.rowdata
     *
     * @return the value of PNMessage.rowdata
     *
     * @mbggenerated
     */
    public String getRowdata() {
        return rowdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PNMessage.rowdata
     *
     * @param rowdata the value for PNMessage.rowdata
     *
     * @mbggenerated
     */
    public void setRowdata(String rowdata) {
        this.rowdata = rowdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PNMessage.addTime
     *
     * @return the value of PNMessage.addTime
     *
     * @mbggenerated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PNMessage.addTime
     *
     * @param addTime the value for PNMessage.addTime
     *
     * @mbggenerated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PNMessage.modTime
     *
     * @return the value of PNMessage.modTime
     *
     * @mbggenerated
     */
    public String getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PNMessage.modTime
     *
     * @param modTime the value for PNMessage.modTime
     *
     * @mbggenerated
     */
    public void setModTime(String modTime) {
        this.modTime = modTime;
    }
}